# Generated by Django 4.2.2 on 2023-07-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_contacto_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
